// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
.ffffff.....ffffff.
ff1fffff...ff1fffff
f111f.ff...f111f.ff
f111f......f111f...
fd11ffffffffd11f...
fddffffffffffddf...
ffffffffffffffff...
..fff1ffffff1f.....
..fff11ffff11f.....
..ffff1ffff1ff.....
..ffff1ffff1ff.....
..ffffffffffff.....
..ffffffffffff.....
...ffffffffff......
....ffffffff.......
...................
...................
`, img`
...................
.ffffff.....ffffff.
ff1fffff...ff1fffff
f111f.ff...f111f.ff
f111f......f111f...
fd11ffffffffd11f...
fddffffffffffddf...
ffffffffffffffff...
..fff1ffffff1f.....
..fff11ffff11f.....
..ffff1ffff1ff.....
..ffff1ffff1ff.....
..ffffffffffff.....
..ffffffffffff.....
...ffffffffff......
....ffffffff.......
...................
`, img`
...................
...................
.ffffff.....ffffff.
ff1fffff...ff1fffff
f111f.ff...f111f.ff
f111f......f111f...
fd11ffffffffd11f...
fddffffffffffddf...
ffffffffffffffff...
..fff1ffffff1f.....
..fff11ffff11f.....
..ffff1ffff1ff.....
..ffff1ffff1ff.....
..ffffffffffff.....
..ffffffffffff.....
...ffffffffff......
....ffffffff.......
`, img`
...................
.ffffff.....ffffff.
ff1fffff...ff1fffff
f111f.ff...f111f.ff
f111f......f111f...
fd11ffffffffd11f...
fddffffffffffddf...
ffffffffffffffff...
..fff1ffffff1f.....
..fff11ffff11f.....
..ffff1ffff1ff.....
..ffff1ffff1ff.....
..ffffffffffff.....
..ffffffffffff.....
...ffffffffff......
....ffffffff.......
...................
`, img`
.ffffff.....ffffff.
ff1fffff...ff1fffff
f111f.ff...f111f.ff
f111f......f111f...
fd11ffffffffd11f...
fddffffffffffddf...
ffffffffffffffff...
..fff1ffffff1f.....
..fff11ffff11f.....
..ffff1ffff1ff.....
..ffff1ffff1ff.....
..ffffffffffff.....
..ffffffffffff.....
...ffffffffff......
....ffffffff.......
...................
...................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
